# Generated by Django 5.0.6 on 2024-08-04 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quote", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(default=0, unique=True)),
                ("label", models.CharField(max_length=35, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("mesure", models.CharField(max_length=50, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rawProducts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawProductsConsumed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, null=True)),
                ("quantity_by_product", models.FloatField(null=True)),
                ("mesure", models.CharField(max_length=50, null=True)),
                ("cost", models.FloatField(null=True)),
                ("number_of_products", models.IntegerField(null=True)),
                ("total_quantity", models.FloatField(null=True)),
                ("total_cost", models.FloatField(null=True)),
                (
                    "quote_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rawproductsconsumed_set",
                        to="quote.quotedetails",
                    ),
                ),
            ],
        ),
    ]
