# Generated by Django 5.0.6 on 2024-08-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rawProducts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawproduct",
            name="owner",
        ),
    ]
