# Generated by Django 5.0.6 on 2024-08-13 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawProducts", "0002_remove_rawproduct_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rawproductsconsumed",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raws_consumed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
