# Generated by Django 5.0.6 on 2024-08-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rawProducts", "0003_rawproductsconsumed_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawproductsconsumed",
            name="owner",
        ),
    ]
