# Generated by Django 5.0.6 on 2024-08-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawProducts", "0004_remove_rawproductsconsumed_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawproductsconsumed",
            name="code",
            field=models.IntegerField(null=True),
        ),
    ]
