# Generated by Django 5.0.6 on 2024-08-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawProducts", "0005_rawproductsconsumed_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawproduct",
            name="length",
            field=models.FloatField(default=0),
        ),
    ]
