# Generated by Django 5.0.6 on 2024-09-05 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawProducts", "0007_rawproduct_owner_rawproductsconsumed_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawproduct",
            name="code",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="rawproduct",
            name="length",
            field=models.FloatField(default=1),
        ),
        migrations.AddConstraint(
            model_name="rawproduct",
            constraint=models.UniqueConstraint(
                fields=("owner", "code"), name="unique_code_per_author"
            ),
        ),
    ]
