# Generated by Django 5.0.6 on 2024-09-05 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawProducts", "0008_alter_rawproduct_code_alter_rawproduct_length_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawproduct",
            name="code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="rawproduct",
            name="label",
            field=models.CharField(max_length=35),
        ),
        migrations.AddConstraint(
            model_name="rawproduct",
            constraint=models.UniqueConstraint(
                fields=("owner", "label"), name="unique_label_per_author"
            ),
        ),
    ]
