# Generated by Django 5.0.6 on 2024-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawProducts", "0009_alter_rawproduct_code_alter_rawproduct_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawproduct",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rawproductsconsumed",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
