# Generated by Django 5.0.6 on 2024-08-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0004_quote_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
