# Generated by Django 5.0.6 on 2024-09-05 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0006_rename_author_quote_owner_quotedetails_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="reference",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.UniqueConstraint(
                fields=("owner", "reference"), name="unique_reference_per_owner"
            ),
        ),
    ]
