# Generated by Django 5.0.6 on 2024-09-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0007_alter_quote_reference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotedetails",
            name="volet_roulant",
        ),
    ]
