# Generated by Django 5.0.6 on 2024-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0008_remove_quotedetails_volet_roulant"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quotedetails",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
