# Generated by Django 5.0.6 on 2024-08-31 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productDetails", "0001_initial"),
        ("products", "0002_remove_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
