# Generated by Django 5.0.6 on 2024-09-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productDetails", "0002_alter_productdetails_product"),
        ("rawProducts", "0006_rawproduct_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetails",
            name="raw_product",
        ),
        migrations.AddField(
            model_name="productdetails",
            name="raw_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rawProducts.rawproduct",
            ),
        ),
    ]
