# Generated by Django 5.0.6 on 2024-09-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productDetails", "0003_remove_productdetails_raw_product_and_more"),
        ("products", "0002_remove_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
    ]
