# Generated by Django 5.0.6 on 2024-10-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productDetails", "0005_productdetails_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
