# Generated by Django 5.0.6 on 2024-10-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productDetails", "0006_productdetails_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productdetails",
            old_name="quantity",
            new_name="slices_quantity",
        ),
    ]
