# Generated by Django 5.0.6 on 2024-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productDetails", "0007_rename_quantity_productdetails_slices_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
