# Generated by Django 5.0.6 on 2024-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scraps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField()),
                ("label", models.CharField(max_length=35)),
                ("length", models.FloatField()),
                ("mesure", models.CharField(max_length=35)),
            ],
        ),
    ]
