# Generated by Django 5.0.6 on 2024-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraps", "0002_scraps_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraps",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
