# Generated by Django 5.0.6 on 2024-09-05 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_code_product_unique_code_per_owner"),
        ("productsFamilly", "0004_alter_productfamilly_label_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="label",
            field=models.CharField(max_length=35),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("owner", "label"), name="unique_label_per_owner"
            ),
        ),
    ]
