# Generated by Django 5.0.6 on 2024-09-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_label_product_unique_label_per_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="label",
            field=models.CharField(max_length=60),
        ),
    ]
