# Generated by Django 5.0.6 on 2024-09-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
    ]
