# Generated by Django 5.0.6 on 2024-10-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_product_is_deleted_product_deleted_at"),
        ("productsFamilly", "0006_remove_productfamilly_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="familly",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productsFamilly.productfamilly",
            ),
        ),
    ]
