# Generated by Django 5.0.6 on 2024-07-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductFamilly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(default=0, unique=True)),
                ("label", models.CharField(max_length=35, unique=True)),
            ],
        ),
    ]
