# Generated by Django 5.0.6 on 2024-09-05 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productsFamilly", "0002_productfamilly_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfamilly",
            name="code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="productfamilly",
            constraint=models.UniqueConstraint(
                fields=("owner", "code"), name="unique_code_per_user"
            ),
        ),
    ]
