# Generated by Django 5.0.6 on 2024-09-05 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productsFamilly", "0003_alter_productfamilly_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfamilly",
            name="label",
            field=models.CharField(max_length=35),
        ),
        migrations.AddConstraint(
            model_name="productfamilly",
            constraint=models.UniqueConstraint(
                fields=("owner", "label"), name="unique_label_per_user"
            ),
        ),
    ]
