# Generated by Django 5.0.6 on 2024-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productsFamilly", "0004_alter_productfamilly_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfamilly",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
